Added new links and title display
nimi-app/card pull request #70
Opened 2022-08-25 21:42 UTC by Mi-Lan

2022-08-25 21:43 UTC, Mi-Lan commented on src/library/utils/index.ts
> +  if (nimi.title) return nimi.title;
@adamazad Any suggestion how to handle the link tittle better?

2022-08-25 23:25 UTC, adamazad requested changes

2022-08-25 23:25 UTC, adamazad commented on src/library/assets/svg/links/snapchat.svg
> +</svg>
Where did we get the logos from? Snapshot logo doesn't look crisp

2022-08-25 23:25 UTC, adamazad commented on src/library/types/NimiLink.ts
> +  /**
Typo 
```suggestion
  /**
   * Messenger Profile
   */
  MESSENGER = 'MESSENGER',
  /**
```

2022-08-25 23:25 UTC, adamazad commented on src/library/types/NimiLink.ts
> +  DRIBBLE = 'DRIBBLE',
Typo 
```suggestion
  DRIBBBLE = 'DRIBBBLE',
```

2022-08-25 23:25 UTC, adamazad commented on public/data.json
> +    { "type": "URL", "title": "Website", "content": "" },
Add a URL here

2022-08-25 23:25 UTC, adamazad commented on src/library/assets/svg/links/dribble.svg
> +</svg>
Filename typoe

2022-08-25 23:25 UTC, adamazad commented on src/library/constants/index.tsx
> +import { ReactComponent as DribbleLogo } from '../assets/svg/links/dribble.svg';
Typo

2022-08-25 23:25 UTC, adamazad commented on src/library/utils/index.ts
> +  if (nimi.title) return nimi.title;
I believe this is good. `title` property has the highest precedence.

2022-08-29 20:14 UTC, Mi-Lan commented on src/library/assets/svg/links/snapchat.svg
> +</svg>
you mean snapchat...yes its from figma maybe zett intended it like that https://www.figma.com/file/IhAXgag9wFFBLLCW7pkv6i/Nimi-%7C-Devconnect-AMS-2022?node-id=1436%3A41065

2022-08-29 22:27 UTC, adamazad approved these changes
Address the comments and merge. Good work!

2022-08-29 22:27 UTC, adamazad commented on public/data.json
> +    { "type": "FIGMA", "title": "Lenster", "content": "luduvigo.lens" },
```suggestion
    { "type": "FIGMA", "title": "Figma", "content": "luduvigo" },
```

?

2022-08-29 22:27 UTC, adamazad commented on src/library/app/index.tsx
> +  console.log('filtered', filterEmptyFields);
You can wrap the console statement in

`process.env.NODE_ENV !== 'development'`

2022-08-29 22:27 UTC, adamazad commented on src/library/utils/index.ts
> +  console.log('modified', nimi);
We should be lean with console statements

2022-08-29 23:14 UTC, merged