Feature: 140 - POAPs Editor
nimi-app/card pull request #83
Opened 2022-09-14 22:05 UTC by bejzik8

# Summary

- created `POAPWidget` component
- updated `NimiPOAPWidget` interface
- updated `POAPWidget` API
- updated `NimiPOAPWidget` validator
- updated `.gitignore` file
- added `Axios` to the project

# Background

All updates are made in order to support working on [`Nimi App`'s Feature 140 - POAPs Editor](https://github.com/nimi-app/app/issues/140).

2022-09-15 09:58 UTC, adamazad commented on src/library/types/NimiWidget.ts
> +  tokens?: string[];
We introduced a `BaseNimiWidget` in https://github.com/nimi-app/card/commit/68fc1810de5320bc8daa52ea045c0644dd0a47bd to standardize the widgets.

2022-09-15 10:11 UTC, bejzik8 commented on src/library/types/NimiWidget.ts
> +  tokens?: string[];
Is there a specific thing you want to achieve by having union-typed context which will provide further nesting instead of having union-typed Widget considering you will handle each widget differently and simplify the things in that way?

2022-09-19 11:31 UTC, adamazad commented
Hey @bejzik8, can you take a look at https://github.com/nimi-app/card/commit/fd9e8c19e4a47d4c72a732eda31e124c5d608c1e? If it sounds good to you, amend the nimi-app PR to it, otherwise, feel free to improve on it.

2022-09-19 13:18 UTC, bejzik8 commented
Sure, I'll take a look and get back to you. I also need some changes in `Nimi Card` in order to handle links reordering properly, I'll include that, as well.

2022-09-21 22:42 UTC, adamazad requested changes

2022-09-21 22:42 UTC, adamazad commented on public/data.json
> +      "tokenIds": ["5388110"]
Revert so the example works.

2022-09-21 22:42 UTC, adamazad commented on src/library/components/NimiCard/NimiCard.renders.tsx
> +  });
Very clean!

2022-09-21 22:42 UTC, adamazad commented on src/library/types/NimiLink.ts
> +  id?: string;
How do we generate these? Linktree uses a numerical ID, what do you think? UTC timestamp?

2022-09-21 22:42 UTC, adamazad commented on src/library/types/NimiWidgetBase.ts
> -}
Restore this file.

2022-09-21 22:42 UTC, adamazad commented on src/library/types/NimiWidget.ts
> +}
The Nimi widget types should extend the available widgets.

2022-09-21 22:42 UTC, adamazad commented on src/library/types/index.ts
> +export * from './POAPToken';
I would like to keep this folder for Nimi types.

2022-09-21 22:42 UTC, adamazad commented on src/library/validators/link.ts
> +  id: Yup.string().optional(),
ID should not be optional ;)

2022-09-21 22:42 UTC, adamazad commented on src/library/validators/validators.ts
> -        context: Yup.object().required(),
Add it back.

2022-09-21 22:42 UTC, adamazad commented on src/library/widgets/POAPWidget/POAPWidget.tsx
> +  widget?: NimiPOAPWidgetContext;
Why is the widget optional?!

2022-09-21 22:42 UTC, adamazad commented on src/library/widgets/POAPWidget/POAPWidget.tsx
> +  ensAddress: string;
Should `address`. The context doesn't matter here.

2022-09-21 22:42 UTC, adamazad commented on src/library/widgets/POAPWidget/POAPWidget.tsx
> +
We're not handling error(s) whatsoever.

2022-09-21 22:42 UTC, adamazad commented on src/library/widgets/POAPWidget/POAPWidget.tsx
> +      <POAPTitle ensAddress={ensAddress} />
Address is address tbf.

2022-09-21 22:42 UTC, adamazad commented on src/library/widgets/POAPWidget/api.ts
> +import axios from 'axios';
I don't see a benefit of Axios if we don't take advantage of error handling.

2022-09-21 22:42 UTC, adamazad commented on src/library/widgets/POAPWidget/api.ts
> +  } finally {
Should do something. i.e. show the error

2022-09-21 22:42 UTC, adamazad commented on src/library/widgets/POAPWidget/api.ts
> +    return fetchedTokens;
Again, this doesn't tell me what happened to my function. Did it fail? Does the user have no POAPs?

2022-09-21 22:42 UTC, adamazad commented on src/library/widgets/POAPWidget/api.ts
> +}
Exact concerns as above.

2022-09-21 22:42 UTC, adamazad commented on src/library/widgets/POAPWidget/components.tsx
> +export const POAPItem = styled.div`
Either export everything or don't export anything at all. Consistency.

2022-09-21 22:42 UTC, adamazad commented on src/library/widgets/POAPWidget/index.tsx
> +// TODO: Adam, do we need this?
No, you can remove it.

2022-09-21 22:42 UTC, adamazad commented on src/library/widgets/poap/types/index.ts
> -export type NimiPOAPWidget = BaseNimiWidget<typeof WidgetTypeId, WidgetContext>;
Again, I think each widget types should here. The design is modular.

2022-09-22 01:19 UTC, bejzik8 commented on src/library/validators/validators.ts
> -        address: Yup.string().required(),
First time using Yup, maybe I'm wrong, I've seen in the documentation that suggested way of using it is by creating schemas and inferring TypeScript types out of those and re-use them across the application and makes a lot of sense to me. You'll have to maintain types only on one place, no code repetition and you can't create clashes during the validation process because on un-synchronisation.

2022-09-22 01:20 UTC, bejzik8 commented on public/data.json
> +      "tokenIds": ["5388110"]
Forgot to update it, sorry! It is done now.

2022-09-22 01:20 UTC, bejzik8 commented on src/library/components/NimiCard/NimiCard.renders.tsx
> +  });
Thanks a lot, didn't expect this from you. 🙏

2022-09-22 01:33 UTC, bejzik8 commented on src/library/types/NimiLink.ts
> +  id?: string;
ATM, this is being used only in `Nimi App`, and creation of link occurs after user opens a AddFieldsModal and clicks on a type of links he wants to add. Id is generated like this `new Date().valueOf().toString()` and currently we are sure that same two can't be created. At some point, if we decide to select a few links and add them at the same time, we can use a different approach, maybe `uuid`.

P.S. We have `key`s error in `Nimi Card`, it might be happening because links don't have a unique ids. This definitely can cause the issues, especially when you add reordering functionality `key={`${type}-${content}`}`. Not sure how you missed it...

2022-09-22 01:47 UTC, bejzik8 commented on src/library/widgets/POAPWidget/api.ts
> +    return fetchedTokens;
I was thinking about this, actually makes sense to keep it this way. If we plan to export functionalities to `Nimi App` only plain fetch call will be exported and this will be packed the same way again, `try` / `catch` / `finally` implementing that call.

I am not sure which kind of feedback do you want to get ATM? You have log in the console which can help you, if we're speaking about the users, implement toast notification and just call it inside `catch` block and it is the right way of using it. You will have an array back.

Advantages of this approach?

- You keep fetching logic extracted from the component and component doesn't care about the implementation
- If you want to switch to e.g. `react-query` or different way of handling this, it is easily achievable
- You don't clutter the component's `useEffect` with `try` / `catch` / `finally` blocks or any other unnecessary logic and you make it more readable
- You get code which is reusable, imagine if you need to use `fetchPOAPs` on another place, you can just import it from there, you can't do that from component's `useEffect` and you don't have to write additional `try` / `catch` / `finally` block
- You get valid data each time and you can count on getting an array.

And again, speaking of consistency, I've seen you use `try` / `catch` / `finally` block somewhere and somewhere you use `.then()` / `.catch()`, makes sense to me to only one approach and I definitely do think the right one is `try` / `catch` / `finally`.

2022-09-22 01:51 UTC, bejzik8 commented on src/library/widgets/POAPWidget/api.ts
> +}
Imagine `showErrorToast("There was an error fetching POAPs.")` instead of `// TODO: HANDLE ERROR`.

P.S. If we're speaking about component's error state handling, we should talk about fetching hooks which I didn't see are being used in the application.

2022-09-22 01:56 UTC, bejzik8 commented on src/library/widgets/POAPWidget/components.tsx
> +export const POAPItem = styled.div`
In case you missed it, `PoapTitle` component is being used only on one place and that is `POAPTitle` function which actually is exported. Components which are exported are being re-used on other places, why would I export something which I don't need anywhere else?

If you want to criticise me for something, do it for poor naming, `PoapTitle` / `POAPTitle`.

2022-09-22 02:00 UTC, bejzik8 commented on src/library/widgets/POAPWidget/index.tsx
> +// TODO: Adam, do we need this?
Done. 👍

2022-09-22 11:38 UTC, adamazad commented on src/library/widgets/POAPWidget/api.ts
> +    return fetchedTokens;
How do you handle the errors, if any? My point stands that API functions should not handle errors. Instead, API consumers — this would be React components, more precisely hooks callbacks such as `useEffect` — should have a way to handle the error.

2022-09-22 11:40 UTC, adamazad commented on src/library/widgets/POAPWidget/api.ts
> +}
> Imagine `showErrorToast("There was an error fetching POAPs.")` instead of `// TODO: HANDLE ERROR`.
> 
> P.S. If we're speaking about component's error state handling, we should talk about fetching hooks which I didn't see are being used in the application.

This is a perfect example of why we want this exact function to throw the error.

2022-09-22 15:16 UTC, bejzik8 commented on src/library/widgets/POAPWidget/POAPWidget.tsx
> +  ensAddress: string;
Context actually matters if tokens are being passed, `address` is removed from context because we already have it as `ensAddress`.

2022-09-22 15:20 UTC, bejzik8 commented on src/library/widgets/POAPWidget/POAPWidget.tsx
> +  widget?: NimiPOAPWidgetContext;
Because it might not exist if there is no `tokenId`s.

2022-09-22 15:23 UTC, bejzik8 commented on src/library/widgets/POAPWidget/api.ts
> +    return fetchedTokens;
Check out `POAPWidget`, detailed explanation is on `Discord`!

2022-09-22 17:27 UTC, adamazad commented on src/library/widgets/POAPWidget/POAPWidget.tsx
> +  widget?: NimiPOAPWidgetContext;
True, extending the types might be cleaner :)

2022-09-22 17:27 UTC, adamazad commented on src/library/widgets/POAPWidget/POAPWidget.tsx
> +  ensAddress: string;
Correct.

2022-09-22 21:29 UTC, adamazad approved these changes

2022-09-22 21:38 UTC, merged